### ISSUE TITLE
Sourcelinks deposit to ME Interface

### ISSUE THREAD

**Issue by Sellular** [62832/ArsEnergistique#15]
When any sourcelink is placed within 5 blocks of an ME Interface (same range as source jar) it sends spare source to the interface once any surrounding source jars or source drives are full, making compact systems like mine end up like this once full of source: 
![image](https://github.com/62832/ArsEnergistique/assets/28738365/a44349ec-13e9-43c1-80db-b6ae0ddac6d2)

Is this intended functionality?

**Comment by Sellular** [comment]
Ars En. V1.1.2 btw

**Comment by 62832** [comment]
Assuming you've already been using an interface to receive source into the network, this is how it should work. I'm afraid I don't know of any way in which it might be prevented from filling up further.

**Comment by Sellular** [comment]
For the time being I've put my interfaces a few blocks away from my source
links. This network subnet is hooked up to my main one which sends out
source to a different subnet for other ars related things using interface
-> storage bus connection. That's probably what did it so interfaces
started getting targeted directly by the sourcelinks if I'm interpreting
your response correctly.

Not sure if you could implement a toggle or something for this
functionality in a config. Directly depositing source from a sourcelinks to
an interface seems a bit odd

**Comment by 62832** [comment]
Now that I remember my own codebase a bit more again, it turns out this is a pretty easy thing to switch off. Not sure when I'll get around to releasing a new build for ArsEng, but expect that next build to no longer have sourcelinks provide source to interfaces or pattern providers.

**Comment by Sellular** [comment]
Thank you!
