### ISSUE TITLE
ME Source Converter not working

### ISSUE THREAD

**Issue by typetetris** [62832/ArsEnergistique#16]
To power my ae2 devices, I configured an ars nouveau relay to take source from a jar and deposit it to the ME Source Converter. Hooked up a charger to the ME Source Converter with a fluix cable.

I can't see any source flowing and both devices, the me source converter and the charger still report as offline.

What am I doing wrong?

Ars 4.10.0
Ars Énergistique 1.1.5
Applied Energistics 2 15.0.20
Forge 47.2.30
Minecraft 1.20.1

Charger <-fluix cable-> ME Source Converter || Air || Relay || Source Jar (100% full)

Relay was configured with a dominion wand by first clicking the jar, then the relay, then clicking the relay again and then clicking the ME Source Converter. A little trail of purplish stars showed for a brief amount of time.

**Comment by 62832** [comment]
Hello. Sorry for not getting back to you on this, but there have been some updates recently since this issue was made and a couple of them were released in order to address other problems with the Source Converter. Would you tell me if these problems still stand on the latest version?

**Comment by typetetris** [comment]
Not playing minecraft any more at the moment sorry. But If i am the only one complaining about this, I probably just did something dumb or didn't use the converter correctly.
