### ISSUE TITLE
Unable to export Source from an Interface

### ISSUE THREAD

**Issue by MuteTiefling** [62832/ArsEnergistique#17]
Ars Energistique: 1.1.5
Minecraft: 1.20.1

Right Click does not set Source to export in an Interface, even though the tooltip indicates it should.
![image](https://github.com/62832/ArsEnergistique/assets/9543430/343ce04f-fc84-43cf-aa4f-778afb993d95)

Works in an Export bus.

As an aside, this method of interacting with Source in the system feels very clunky. It's not obvious that you should use a Source Jar to set an export and feels contrary to any other filter you'd set in AE2 (items and fluids can just be dragged in from JEI). 

As an alternative, I'd suggest a new block, the ME Source Jar.

This source jar would attach directly to the ME network and act as a proxy for the source in the system. You would be able to send to it until the system is full and extract from it until the system is empty. In all other aspects, it would act as a Source Jar.

**Comment by 62832** [comment]
I had considered that the ME Source Jar would indeed be a good addition to the mod, however I never did manage to put that feature together.

In general I feel like I have been neglecting this add-on a lot, so I will try one of these days to sit down and work on it a bit more to address some long-standing sticking points.
