### ISSUE TITLE
Unable to change ae_per_source value above 19 in arseng-common.toml

### ISSUE THREAD

**Issue by sixfoxes** [62832/ArsEnergistique#19]
MC 1.20.1 
NeoForge 47.1.105
Ars Energistique 1.1.5
Ars Nouveau 4.9.0
AE2 15.2.1

Occurs on both Single player and server-hosted 

On minecraft server side, ae_per_source =19 and below works. 20 and above does not generate AE energy via source using blocks in these configurations (Have not tested others):

source relay > ME Source Acceptor(component size)
ME Exporter (set to export source) > ME Source Acceptor (component size)

Also, source>AE energy generation does not ramp very far above current network usage even when network AE storage has AE capacity available.

**Comment by sixfoxes** [comment]
![2024-06-01_13 11 06](https://github.com/62832/ArsEnergistique/assets/72291578/d0482207-d5dd-4122-bf0a-7b2679bc129b)
![2024-06-01_13 10 46](https://github.com/62832/ArsEnergistique/assets/72291578/66a07027-9c72-4b5a-9b0e-83b95234b0cb)
![2024-06-01_13 10 25](https://github.com/62832/ArsEnergistique/assets/72291578/78c4acc3-3740-4a77-8110-d3ce4bc04afc)

**Comment by sixfoxes** [comment]
![2024-06-01_13 14 26](https://github.com/62832/ArsEnergistique/assets/72291578/64110db2-dde2-4fab-b9f5-ca75edbd65ac)
set to 19 - now it worky

**Comment by sixfoxes** [comment]
that was fast. Thanks Bro 👍

**Comment by sixfoxes** [comment]
@62832 that was fast! Thanks bro 👍

**Comment by 62832** [comment]
Lucky for you, I had already been working on some back-ports for this mod at the time you opened this issue.

**Comment by sixfoxes** [comment]
@62832 nice. 
also, I tried to compile the source files on my end to and the build failed same as the github build task :(

**Comment by 62832** [comment]
The build only works if you run the `spotlessApply` Gradle task to apply formatting rules.

**Comment by sixfoxes** [comment]
yea I don't know enough to really troubleshoot this. I will wait for you to recompile and release on modrinth or curseforge. Thank you

**Comment by sixfoxes** [comment]
I installed the new version. The mod fails to load. I opened a new issue. @62832 #20
