### ISSUE TITLE
v1.1.6 - Illegal version number specified

### ISSUE THREAD

**Issue by sixfoxes** [62832/ArsEnergistique#20]
MC 1.20.1 
NeoForge 47.1.105 & 47.1.106 (tried both)
Ars Energistique 1.1.6
Ars Nouveau 4.9.0
AE2 15.2.2 
tried both client and server

The mod fails to load. 

[main/ERROR] [loading.moddiscovery.ModDiscoverer/SCAN]: Locator {mods folder locator at C:\Users\Six\AppData\Roaming\PrismLauncher\instances\1.20.2 NEOFORGE\.minecraft\mods} found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@346690d6 net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Illegal version number specified v1.1.6 (arseng-v1.1.6.jar)

https://mclo.gs/WpSCmKz <- log file [mc client]

**Comment by 62832** [comment]
Sorry about that, a working build should be out in the next few minutes.
