### ISSUE TITLE
256k ME Source Storage Cell is actually a 25 600, and not 256k.

### ISSUE THREAD

**Issue by Ranzuu** [62832/ArsEnergistique#23]
![image](https://github.com/62832/ArsEnergistique/assets/66495944/0de2d5f3-feb2-4f7e-9552-56390f3091c4)

**Comment by Ranzuu** [comment]
Observed in Atm9-To the Sky 1.0.7.
ArsEnergistique version 1.1.7

**Comment by 62832** [comment]
Intentional for the time being, as one byte was made to represent 1,000 source. This'll be adjusted in some future major release.
