### ISSUE TITLE
Strange AE filter setting behavior with arseng-1.0.1

### ISSUE THREAD

**Issue by XenonDB** [62832/ArsEnergistique#24]
When set fluid filter for level emitter, it show fluid amount at right bottom corner:
![2024-09-20_15 27 27](https://github.com/user-attachments/assets/3876496b-c7d2-4bd1-adb8-9f2220597f20)
Then close level emitter GUI and open again, the fluid amount setting become 1000x :
![2024-09-20_15 27 38](https://github.com/user-attachments/assets/49f91710-b0f1-4a23-b974-9abe4f4a0536)
Close and open again, it 1000x again.

When setting filter for cell in cell workbench, I can only set one item for a cell:
![2024-09-20_15 29 06](https://github.com/user-attachments/assets/389f0af6-e797-4903-81b0-6e1384df7805)
As shown above, if I first add grass block into filter then add cell workbench into filter, grass block in filter vanish.
In this situation, the only way to set multiple item filter for a cell is first don't put cell into cell workbench and enable copy mode, then set filter in workbench, then put cell into it to copy setting.

These strange behavior don't exist in arseng-1.0.0
Seems 1.0.1 make something broken.

**Comment by 62832** [comment]
This was already fixed in 1.1.7 but I have not managed to backport that to 1.19. I'm not entirely sure if I would even like to considering there is next to no demand left for anything to do with that version.
