### ISSUE TITLE
Ars Energistique (arseng) has failed to load correctly 

### ISSUE THREAD

**Issue by Nile737** [62832/ArsEnergistique#26]
[crash-2024-10-19_22.10.37-fml.txt](https://github.com/user-attachments/files/17448116/crash-2024-10-19_22.10.37-fml.txt)

Not at all sure what happend.

**Comment by 62832** [comment]
I was made aware that the current released version of Ars Nouveau does not yet have something that Ars Énergistique relies on. If you wait for another release of Ars Nouveau and/or update it should be fine.

**Comment by 62832** [comment]
Can you confirm whether this still happens with Ars Nouveau 5.2.0?
