### ISSUE TITLE
[1.21.1] Crash when linking a Source Relay to an ME Source Converter

### ISSUE THREAD

**Issue by MuteTiefling** [62832/ArsEnergistique#27]
Crash when linking a Source Relay to an ME Source Converter

1. Place Source Converter on an ME network
2. Place jar full of source
3. Place relay
4. Link jar to relay
5. link relay to converter
6. crash

https://gist.github.com/MuteTiefling/d831f84ce0f8e26e9a5482a4ba7f4a42

**Comment by 62832** [comment]
Fixed in 30ef7e6f442b2328742001b58a70232490110ca5.

**Comment by MuteTiefling** [comment]
Awesome, thanks!
