### ISSUE TITLE
[1.21.1] Source Acceptor doesn't appear to work

### ISSUE THREAD

**Issue by MuteTiefling** [62832/ArsEnergistique#28]
Cannot bind anything to the Source Acceptor and it doesn't even appear to take up a channel

![image](https://github.com/user-attachments/assets/98fe98d0-c322-4cde-8e50-23aaab9c32ab)

![image](https://github.com/user-attachments/assets/c486a4d6-f5b1-4ed7-ad8b-8faebf82fc2a)

**Comment by MuteTiefling** [comment]
Actually, probably the same issue as https://github.com/62832/ArsEnergistique/issues/27. I still have the neoforge option on to yeet erroring tile entities and I did actually get an error in the latest log when I hooked this up.

**Comment by 62832** [comment]
This is in fact an Ars Nouveau problem at the moment due to the fact that while it does now offer a directional block capability, Ars never queries it for relays with any actual `Direction` context other than `null`.
