### ISSUE TITLE
A bug that prevents me from breaking the ME interface

### ISSUE THREAD

**Issue by NianGuu** [62832/ArsEnergistique#3]
![image](https://github.com/62832/ArsEnergistique/assets/101057381/29788a25-6dfa-4ddf-aa6b-ae7caede7aff)
As shown in the figure.
When I try to destroy a ME interface that has transported source, it turns out like this and I cannot break it.

**Comment by NianGuu** [comment]
a crash
[crash-2023-08-24_12.44.38-server.txt](https://github.com/62832/ArsEnergistique/files/12425500/crash-2023-08-24_12.44.38-server.txt)

**Comment by 62832** [comment]
That's not good. Would you mind providing some exact steps to reproduce this so I can provide a fix?

**Comment by 62832** [comment]
Also, are you certain the crash log provided is related to the interface? The first line I see there points to the Source Acceptor instead.

If that's a different issue, then please report it separately.

**Comment by NianGuu** [comment]
> 另外，您确定提供的崩溃日志与接口有关吗？我在那里看到的第一行指向源接受器。
> 
> 如果这是一个不同的问题，那么请记住在以后单独报告。但是，我相信我刚才已经修复了这个问题。

This is not the same bug, I just place them in the same issues. To reproduce the first bug, you only need to pass the source once in the ME interface.the second, I don't know how to reproduce it .

**Comment by NianGuu** [comment]
> Also, are you certain the crash log provided is related to the interface? The first line I see there points to the Source Acceptor instead.
> 
> If that's a different issue, then please remember to report it separately in the future. I believe I've already fixed this one just now, however.

This is not the same bug, I just place them in the same issues. To reproduce the first bug, you only need to pass the source once in the ME interface.the second, I don't know how to reproduce it .

**Comment by NianGuu** [comment]
> Also, are you certain the crash log provided is related to the interface? The first line I see there points to the Source Acceptor instead.
> 
> If that's a different issue, then please remember to report it separately in the future. I believe I've already fixed this one just now, however.

you fixed it ! Good job.
