### ISSUE TITLE
How am I supposed to export Source?

### ISSUE THREAD

**Issue by Jakub-Wilk** [62832/ArsEnergistique#5]
Source as a fluid doesn't show up in either JEI or REI. How am I supposed to drag it into the export bus?

**Comment by 62832** [comment]
Use a Source Jar. The rest should be self-explanatory.

**Comment by TheAmazingJeh** [comment]
For some reason that won't work for me, I have this set up (to test) and have set the filter as a source jar, what did I do wrong? (This is in the ATM Volcano Block Modpack btw)

![image](https://github.com/62832/ArsEnergistique/assets/81706323/9163f9da-1587-47cb-a907-8d2dd2a95380)
![image](https://github.com/62832/ArsEnergistique/assets/81706323/b16aeb50-09ba-4509-ac0b-8bdaa7ecc345)

**Comment by 62832** [comment]
You're supposed to *right-click* with a Source Jar. The tooltip you would have gotten when hovering with the jar should have told you this.

**Comment by TheAmazingJeh** [comment]
Thanks, I missed the tooltip when trying to set the filter, It might be useful to say something about it in the guide book so people like me don't miss it. :)
