### ISSUE TITLE
Extract the storage component from a source cell

### ISSUE THREAD

**Issue by Cyakat** [62832/ArsEnergistique#9]
It would be nice to be able to shift right click a source cell and get the storage component back like with other AE2 cells.

**Comment by 62832** [comment]
...shit, did I forget about this altogether?

**Comment by Cyakat** [comment]
Not completely. It didn't work with the 64k drive. I can't say anything about the other drives but I know it does work with the portable drive. I am on 1.19.2 if that is any help.
